### ISSUE TITLE
license attribution

### ISSUE THREAD

**Issue by lukeed** [htdangkhoa/pure-http#288]
Hi there,

Your [`regexToParams`](https://github.com/htdangkhoa/pure-http/blob/daf2b7c17400bcd7bf9ab84d64e54ccd31b04665/lib/utils.js#L1-L41) utility function is a 100% copy-paste of my [`regexparam`](https://github.com/lukeed/regexparam) library.

I understand you're trying to have "zero dependencies", but please either list this as a dependency or include a copy of my library's license.

As of now, you're violating [the MIT license](https://github.com/lukeed/regexparam/blob/main/license), which `regexparam` is protected by & distributed under.

> Edit: Specifically, the [`regexparam@2.x`](https://github.com/lukeed/regexparam/blob/v2.0.2/src/index.js) release track. All you've done is expand variable declarations onto new lines, change `var` to `let`, remove some double-negations (`!!`), and replace string concatenation with template literals.

**Comment by htdangkhoa** [comment]
Hi @lukeed,
First of all, I apologize for responding to you late.
Next, I would also like to apologize for the omission in copyright issues. In an update in the next few days, I will attach copyright information where I have used it.

Once again, I really appreciate your contribution and will learn from it for myself in the future!
