### ISSUE TITLE
Drop-in replacement for Express?

### ISSUE THREAD

**Issue by aral** [htdangkhoa/pure-http#50]
Just stumbled on this and love your approach to have a lightweight/no-dependency server. Given how similar the API looks to Express I wanted to see if I could just replace my import line and have it run but saw that pure-http returns a Server instance whereas Express returns the listener function.

Thinking that if it was a plug-and-play replacement of Express, it would make it much easier to existing projects to adopt.

(Barring that, do you have any thoughts/docs on migration?)

Thanks again for making/sharing this. Even if I can’t use it on my current app, I’ll definitely keep it in mind for the future and let others know :)

**Comment by htdangkhoa** [comment]
Hi @aral , thanks for your interest in `pure-http`.

In essence, `Express` still returns a Server instance, you can take a look at [`application.js`](https://github.com/expressjs/express/blob/master/lib/application.js#L616) and [`server.listen()`](https://nodejs.org/api/http.html#http_server_listen).

**Comment by aral** [comment]
Thanks, I’ll give it a shot when I next get a moment. Appreciate the pointer :)
